### ISSUE TITLE
HDD Light Control

### ISSUE THREAD

**Issue by talbottmd** [bkram/mytoolbox#1]
This code is awesome and super useful to my setup. Any chance the HDD LEDs can also be controlled through this interface or do you happen to know what mechanism controls them?

**Comment by bkram** [comment]
Hi,

No the HDD leds cannot be controlled, 

This seems specific to the kernels QNAP delivers.

See the discussion http://www.gossamer-threads.com/lists/linux/kernel/1799465 here for more information.
